[build]
  functions = "netlify/functions"

[functions]
  external_node_modules = ["mongodb"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
